name: "Org Knit"
description: "Weave and Tangle Org files"
branding:
  icon: "shuffle"
  color: "white"
inputs:
  config:
    description: Emacs config to use with the export
    default: false
  setup_file:
    description: Setupfile to apply to all exported files
    default: false
  eval:
    description: Bool indicating whether to allow evaluation of code blocks during export, or a list of files.
    default: false
  tangle:
    description: Bool indicating whether to run org-tangle on each file, or a list of files to tangle.
    default: false
  export:
    description: List of formats to export to.
    default: "html"
  files:
    description: List of Org file globs to act on. All .org files by default
    default: "**/*.org"
  github_token:
    description: Use the generated GITHUB_TOKEN for pushing to the remote branch.
    default: false
  branch:
    description: Branch to push files to. Will use the default branch unless told otherwise.
    default: true
  force_orphan:
    description: Keep only the latest commit on the specified branch.
    default: false
  keep_files:
    description: When using a non-default branch, keep non-org-related files.
    default: true
  commit_message:
    description: 'Commit message to use. "!#!" is replaced with the triggering commit''s short hash.'
    default: "Knit: !#!"
  fragile:
    description: Fail the action at the first sign of trouble, or power on through.
    default: true

runs:
  using: "docker"
  image: "docker://ghcr.io/tecosaur/org-knit-action:v0.3"
  args:
    - ${{ inputs.config }}
    - ${{ inputs.setupfile }}
    - ${{ inputs.eval }}
    - ${{ inputs.tangle }}
    - ${{ inputs.export }}
    - ${{ inputs.files }}
    - ${{ inputs.github_token }}
    - ${{ inputs.branch }}
    - ${{ inputs.force_orphan }}
    - ${{ inputs.keep_files }}
    - ${{ inputs.commit_message }}
    - ${{ inputs.fragile }}
